# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "influxdb"
version = "0.1.0"
authors = ["Gero Gerke <11deutron11@gmail.com>"]
edition = "2018"
description = "InfluxDB Driver for Rust"
keywords = ["influxdb", "database", "influx"]
license = "MIT"
readme = "README.md"
include = ["src/**/*", "tests/**/*", "Cargo.toml", "LICENSE"]
repository = "https://github.com/Empty2k12/influxdb-rust"

[badges]
travis-ci = { repository = "Empty2k12/influxdb-rust", branch = "master" }

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] } 
failure = "0.1.7"
futures = "0.3.4"
influxdb_derive = { version = "0.1.0", optional = true }
reqwest = { version = "0.10.4", features = ["json"] }
serde = { version = "1.0.104", features = ["derive"], optional = true }
serde_json = { version = "1.0.48", optional = true }
regex = "1.3.5"
lazy_static = "1.4.0"
smol_str = { version = "0.1.16", optional = true, features = ["serde"] }

[features]
use-serde = ["serde", "serde_json", "smol_str"]
default = ["use-serde"]
derive = ["influxdb_derive"]

[dev-dependencies]
tokio = { version =  "0.2.11", features = ["macros"] }
maplit = "1.0.2"
